/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package view;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maria
 */
public class AdminPanel extends javax.swing.JFrame {
    
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountLabel = new javax.swing.JLabel();
        istructionsLabel1 = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        deleteUserButton = new javax.swing.JButton();
        titleTextField = new javax.swing.JTextField();
        authorTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        genreTextField = new javax.swing.JTextField();
        amountTextField = new javax.swing.JTextField();
        changeBookTextField = new javax.swing.JTextField();
        addBookButton1 = new javax.swing.JButton();
        viewBookButton = new javax.swing.JButton();
        viewUsersButton = new javax.swing.JButton();
        deleteBookButton2 = new javax.swing.JButton();
        passwordLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        adminTextField = new javax.swing.JTextField();
        changeBookButton = new javax.swing.JButton();
        changeUserButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();
        istructionsLabel2 = new javax.swing.JLabel();
        changeUserTextField = new javax.swing.JTextField();
        viewSellingsButton1 = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        CSVButton = new javax.swing.JButton();
        istructionsLabel3 = new javax.swing.JLabel();
        PDFButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bookstore-AdminPannel");
        setBackground(new java.awt.Color(255, 204, 204));

        amountLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        amountLabel.setText("Amount:");

        istructionsLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        istructionsLabel1.setText("Book you want to update\\delete:");

        authorLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        authorLabel.setText("Author:");

        priceLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        priceLabel.setText("Price:");

        titleLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        titleLabel.setText("Title:");

        yearLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        yearLabel.setText("Year:");

        genreLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        genreLabel.setText("Genre:");

        deleteUserButton.setBackground(new java.awt.Color(255, 204, 204));
        deleteUserButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        deleteUserButton.setText("Delete user!");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        changeBookTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBookTextFieldActionPerformed(evt);
            }
        });

        addBookButton1.setBackground(new java.awt.Color(255, 204, 204));
        addBookButton1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        addBookButton1.setText("Add book!");
        addBookButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButton1ActionPerformed(evt);
            }
        });

        viewBookButton.setBackground(new java.awt.Color(255, 204, 204));
        viewBookButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        viewBookButton.setText("View Books");
        viewBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookButtonActionPerformed(evt);
            }
        });

        viewUsersButton.setBackground(new java.awt.Color(255, 204, 204));
        viewUsersButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        viewUsersButton.setText("View Users");
        viewUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsersButtonActionPerformed(evt);
            }
        });

        deleteBookButton2.setBackground(new java.awt.Color(255, 204, 204));
        deleteBookButton2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        deleteBookButton2.setText("Delete book!");
        deleteBookButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookButton2ActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        passwordLabel.setText("Password:");

        emailLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        emailLabel.setText("Email:");

        adminLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        adminLabel.setText("Admin:");

        nameLabel.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        nameLabel.setText("Name:");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        adminTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTextFieldActionPerformed(evt);
            }
        });

        changeBookButton.setBackground(new java.awt.Color(255, 204, 204));
        changeBookButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        changeBookButton.setText("Update book!");
        changeBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBookButtonActionPerformed(evt);
            }
        });

        changeUserButton.setBackground(new java.awt.Color(255, 204, 204));
        changeUserButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        changeUserButton.setText("Update user!");
        changeUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserButtonActionPerformed(evt);
            }
        });

        addUserButton.setBackground(new java.awt.Color(255, 204, 204));
        addUserButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        addUserButton.setText("Add user!");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        istructionsLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        istructionsLabel2.setText("User you want to update\\delete:");

        changeUserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserTextFieldActionPerformed(evt);
            }
        });

        viewSellingsButton1.setBackground(new java.awt.Color(255, 204, 204));
        viewSellingsButton1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        viewSellingsButton1.setText("View Sellings");
        viewSellingsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSellingsButton1ActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(255, 204, 204));
        logoutButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        logoutButton.setText("LOG-OUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        CSVButton.setBackground(new java.awt.Color(255, 204, 204));
        CSVButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        CSVButton.setText("CSV");
        CSVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVButtonActionPerformed(evt);
            }
        });

        istructionsLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        istructionsLabel3.setText("Reports:");

        PDFButton.setBackground(new java.awt.Color(255, 204, 204));
        PDFButton.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        PDFButton.setText("PDF");
        PDFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(amountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(authorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(viewUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(adminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(85, 85, 85))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(viewSellingsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(117, 117, 117))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(changeUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(changeUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(551, 551, 551)
                        .addComponent(istructionsLabel2)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(istructionsLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(istructionsLabel3)
                                .addGap(68, 68, 68)
                                .addComponent(CSVButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(yearTextField)
                                    .addComponent(priceTextField)
                                    .addComponent(genreTextField)
                                    .addComponent(amountTextField))
                                .addComponent(changeBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(viewBookButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBookButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBookButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PDFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(887, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {viewBookButton, viewSellingsButton1, viewUsersButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(istructionsLabel3)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CSVButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PDFButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addComponent(istructionsLabel1)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(istructionsLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminLabel)
                            .addComponent(adminTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(titleLabel)
                                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deleteBookButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabel))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(authorLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yearLabel)
                                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceLabel)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(passwordLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genreLabel)
                            .addComponent(genreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBookButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountLabel)
                            .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewSellingsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {viewBookButton, viewSellingsButton1, viewUsersButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserButtonActionPerformed

    private void changeBookTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBookTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeBookTextFieldActionPerformed

    private void addBookButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBookButton1ActionPerformed

    private void viewBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBookButtonActionPerformed

    private void viewUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewUsersButtonActionPerformed

    private void deleteBookButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBookButton2ActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void adminTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminTextFieldActionPerformed

    private void changeBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBookButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeBookButtonActionPerformed

    private void changeUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeUserButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void changeUserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeUserTextFieldActionPerformed

    private void viewSellingsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSellingsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewSellingsButton1ActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void CSVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSVButtonActionPerformed

    private void PDFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDFButtonActionPerformed
    public void eroare()
    {
        JOptionPane.showMessageDialog(null, "Eroare");
    }
    
    public void succes()
    {
        JOptionPane.showMessageDialog(null, "Operatie efectuata cu succes");
    }
    public void afisareTabel(DefaultTableModel tabel)
    {
        JTable userTable=new JTable(tabel);
        JDialog dialog=new JDialog();
        dialog.setPreferredSize(new Dimension(650,300));
        dialog.setLocationRelativeTo(null);
        dialog.setTitle("Books");
        JScrollPane scrollPane3 = new JScrollPane(userTable);
        scrollPane3.setBounds(10, 50, 950, 120);
        scrollPane3.setEnabled(false);
        dialog.add(scrollPane3);
        dialog.pack();
        dialog.setVisible(true);
    }
    public void addBooks(ActionListener metoda)
    {
        addBookButton1.addActionListener(metoda);
    }
    //-------------------------BOOKS----------------------------------------------------
    public void updateBooks(ActionListener metoda)
    {
        changeBookButton.addActionListener(metoda);
    }
    public void deleteBooks(ActionListener metoda)
    {
        deleteBookButton2.addActionListener(metoda);
    }
    public void showBooks(ActionListener metoda)
    {
        viewBookButton.addActionListener(metoda);
    }
    public String getTitleTextField()
    {
        return titleTextField.getText();
    }
    
    public String getAutorTextField()
    {
        return authorTextField.getText();
    }
    public String getYearTextField()
    {
        return yearTextField.getText();
    }
    public String getPriceTextField()
    {
        return priceTextField.getText();
    }
    public String getGenreTextField()
    {
        return genreTextField.getText();
    }
    public String getAmountTextField()
    {
        return amountTextField.getText();
    }
    public String getChangeBook()
    {
        return changeBookTextField.getText();
    }
    //--------------------------------------USERS----------------------------------
    public String getChangeUser()
    {
        return changeUserTextField.getText();
    }
    public String getNameUser()
    {
        return nameTextField.getText();
    }
    public String getEmailUser()
    {
        return emailTextField.getText();
    }
    public String getAdminUser()
    {
        return adminTextField.getText();
    }
    public String getPwdUser()
    {
        return passwordTextField.getText();
    }
    public void addUser(ActionListener metoda)
    {
        addUserButton.addActionListener(metoda);
    }
    public void deleteUser(ActionListener metoda)
    {
        deleteUserButton.addActionListener(metoda);
    }
    public void updateUser(ActionListener metoda)
    {
        changeUserButton.addActionListener(metoda);
    }
     public void showUsers(ActionListener metoda)
    {
        viewUsersButton.addActionListener(metoda);
    }
      public void showSellings(ActionListener metoda)
    {
        viewSellingsButton1.addActionListener(metoda);
    }
      
      public void logut(ActionListener metoda)
    {
        logoutButton.addActionListener(metoda);
    }
      public void CSV(ActionListener metoda)
    {
        CSVButton.addActionListener(metoda);
    }
      public void PDF(ActionListener metoda)
    {
        PDFButton.addActionListener(metoda);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CSVButton;
    private javax.swing.JButton PDFButton;
    private javax.swing.JButton addBookButton1;
    private javax.swing.JButton addUserButton;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JTextField adminTextField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JButton changeBookButton;
    private javax.swing.JTextField changeBookTextField;
    private javax.swing.JButton changeUserButton;
    private javax.swing.JTextField changeUserTextField;
    private javax.swing.JButton deleteBookButton2;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JTextField genreTextField;
    private javax.swing.JLabel istructionsLabel1;
    private javax.swing.JLabel istructionsLabel2;
    private javax.swing.JLabel istructionsLabel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTextField;
    private javax.swing.JButton viewBookButton;
    private javax.swing.JButton viewSellingsButton1;
    private javax.swing.JButton viewUsersButton;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
